---
- include: ../../debrepos/playbooks/nodejs.yml
- apt: pkg=nodejs state=present
- file: path=/usr/local/bin/{{ item }}
        state=link
        src=/usr/bin/{{ item }}
  with_items:
    - node
    - npm
