---
- include: ../../utils/playbooks/base.yml
- name: Install NVM
  shell: /usr/bin/curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | /bin/sh
         creates=/home/{{ username }}/.nvm/nvm.sh
         chdir=/home/{{ username }}
  sudo_user: "{{ username }}"
