---
- shell: /bin/sed -i "s/{{ default_ubuntu_mirror }}/{{ ubuntu_mirror }}/g" /etc/apt/sources.list && touch /root/.apt-mirror-update
         creates=/root/.apt-mirror-update
- name: Update Apt if cache more than one week old
  apt: update_cache=yes cache_valid_time=604800
  async: 900
  poll: 10

