# RPMs of various GIS applications for Enterpris Linux and derivatives
---
- yum: name={{ item }} state=present
  with_items:
    - ansible
    - redhat-lsb-core
- yum: name=/vagrant-share/repos/elgis-release-6-6_0.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 6
- yum: name=/vagrant-share/repos/elgis-release-5-5_0.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 5

