---
- include: ../../utils/playbooks/inotifylimit.yml
- include: ../../java/playbooks/oraclejdk7.yml
- get_url: url=http://download-ln.jetbrains.com/idea/idea{{ idea_edition }}-{{ idea_version }}.tar.gz
           dest=/vagrant-share/apps/idea{{ idea_edition }}-{{ idea_version }}.tar.gz
           sha256sum={{ idea_sha256sum }}
  async: 1800
  poll: 10
- command: /bin/tar -zxf /vagrant-share/apps/idea{{ idea_edition }}-{{ idea_version }}.tar.gz --directory=/opt
           creates=/opt/idea-{{ idea_edition }}-{{ idea_build }}/bin
- file: path=/opt/idea{{ idea_edition }} state=link src=/opt/idea-{{ idea_edition }}-{{ idea_build }}
- file: path=/usr/local/bin/idea{{ idea_edition }}.sh state=link src=/opt/idea{{ idea_edition }}/bin/idea.sh
- copy: src=../../../share/conf/idea/idea{{ idea_edition }}.desktop
        dest=/home/{{ username }}/Desktop/idea{{ idea_edition }}.desktop
        mode=0775 owner={{ username }} group={{ username }}
- file: path=/home/{{ username }}/{{ item }}
        state=directory
        mode=0775 owner={{ username }} group={{ username }}
  with_items:
    - "{{ idea_config_dir }}"
    - "{{ idea_config_dir }}/config"
    - "{{ idea_config_dir }}/config/options"
- copy: src=../../../share/conf/idea/disabled_plugins.txt
        dest=/home/{{ username }}/{{ idea_config_dir }}/config/disabled_plugins.txt
        force=no mode=0664 owner={{ username }} group={{ username }}
- copy: src=../../../share/conf/idea/jdk7.table.xml
        dest=/home/{{ username }}/{{ idea_config_dir }}/config/options/jdk.table.xml
        mode=0664 owner={{ username }} group={{ username }}
- apt: pkg=gtk2-engines-pixbuf state=present
  when: ansible_os_family == "Debian"
- include: ../../ubuntu/playbooks/keybindings.yml
  when: ansible_os_family == "Debian"

